### PR TITLE
Sync offseason repo to main

### PR DESCRIPTION
**Pull request by jasonballinger**
Also merges in SDR branch changes. We can delete SDR after this merge, everything will be under the main branch.

### CODE REVIEW

**Review by ArshansGithub — APPROVED** [review]
i approve

**Review by ksthakkar — APPROVED** [review]
Merging looks good. Should remove all classes that reference "mace" as well as empty and unused autonomous commands. 

Add comments @ArshansGithub to all autonomous and grabber systems you've worked on for better documentation

**Review by ksthakkar — CHANGES_REQUESTED** [review]
Make changes above

**Comment by ArshansGithub** [comment]
Going to make comments next, I also tried fixing abstraction for autonomous and made it all under one class to make easier to use

**Comment by jasonballinger** [comment]
@ArshansGithub are requested changes finished?

**Comment by ArshansGithub** [comment]
> @ArshansGithub are requested changes finished?

no need to comment code now

**Review by ArshansGithub — APPROVED** [review]
Refactored auto, most changes done but there will always be more to do so might as well just merge this onto main repo. Fixed auto and added some comments. Removed mace stuff and cleaned up everything.

**Pull request merged**
